export const images = {
  instagramLogo: require('../assets/icons/instagramLogo.png'),
  eye: require('../assets/icons/eye.png'),
  hidePass: require('../assets/icons/hidePass.png'),
  google: require('../assets/icons/google.png'),
  down: require('../assets/icons/down.png'),
  add: require('../assets/icons/plus.png'),
  home: require('../assets/icons/home.png'),
  notification: require('../assets/icons/notification.png'),
  profile: require('../assets/icons/user.png'),
  search: require('../assets/icons/search.png'),
  addPost: require('../assets/icons/more.png'),
  menu: require('../assets/icons/hambuger.png'),
  activeSearch: require('../assets/icons/activeSearch.png'),
  activeHome: require('../assets/icons/activeHome.png'),
  activeAddPost: require('../assets/icons/activeAddPost.png'),
  activeNotification: require('../assets/icons/activeNotification.png'),
  activeProfile: require('../assets/icons/activeProfile.png'),
};
