export const images = {
  instagramLogo: require('../assets/icons/instagramLogo.png'),
  eye: require('../assets/icons/eye.png'),
  hidePass: require('../assets/icons/hidePass.png'),
  google: require('../assets/icons/google.png'),
  down: require('../assets/icons/down.png'),
  add: require('../assets/icons/plus.png'),
  home: require('../assets/icons/home.png'),
  notification: require('../assets/icons/notification.png'),
  profile: require('../assets/icons/user.png'),
  search: require('../assets/icons/search.png'),
  addPost: require('../assets/icons/more.png'),
  menu: require('../assets/icons/hambuger.png'),
  activeSearch: require('../assets/icons/activeSearch.png'),
  activeHome: require('../assets/icons/activeHome.png'),
  activeAddPost: require('../assets/icons/activeAddPost.png'),
  activeNotification: require('../assets/icons/activeNotification.png'),
  activeProfile: require('../assets/icons/activeProfile.png'),
  blackAdd: require('../assets/icons/blackAdd.png'),
  whiteAdd: require('../assets/icons/whiteAdd.png'),
  heart: require('../assets/icons/heart.png'),
  redHeart: require('../assets/icons/redHeart.png'),
  whiteHeart: require('../assets/icons/whiteHeart.png'),
  comments: require('../assets/icons/comments.png'),
  whiteComments: require('../assets/icons/whiteChat.png'),
  send: require('../assets/icons/send.png'),
  whiteHome: require('../assets/icons/whiteHome.png'),
  whiteActiveHome: require('../assets/icons/whiteActiveHome.png'),
  whiteSearch: require('../assets/icons/whiteSearch.png'),
  whiteActiveSearch: require('../assets/icons/whiteActiveSearch.png'),
  whiteActiveAddPost: require('../assets/icons/whiteActiveAddPost.png'),
  whiteAddPost: require('../assets/icons/whiteAddPost.png'),
  whiteActiveNotification: require('../assets/icons/whiteActiveNotification.png'),
  whiteNotification: require('../assets/icons/whiteNotification.png'),
  whiteUser: require('../assets/icons/whiteUser.png'),
  whiteActiveUser: require('../assets/icons/whiteActiveUser.png'),
  close: require('../assets/icons/close.png'),
  blackBack: require('../assets/icons/blackBack.png'),
  whiteBack: require('../assets/icons/whiteBack.png'),
};

export const RANDOM_IMAGES = [
  'https://fastly.picsum.photos/id/1011/500/500.jpg?hmac=YN3oCpwpniYpKEclMAlUd1vWTmlpeh6BUdpODrFAINc',
  'https://fastly.picsum.photos/id/1015/500/500.jpg?hmac=LNni84jXVOXdvxYPr-DoeAxRSQnnd-9Sf_-CunUKGYI',
  'https://fastly.picsum.photos/id/1025/500/500.jpg?hmac=-8oa3YhiI2vz-AJSkoxWl_7uP0QpVYMmQabi48iqMHM',
  'https://fastly.picsum.photos/id/1035/500/500.jpg?hmac=VgIFigWEM4x04jktFvmZVXDqJVVq6XHYyTtPX9C8PtQ',
  'https://fastly.picsum.photos/id/1040/500/500.jpg?hmac=bmdEjFeT-uNd51SRuaCY9lKhha5_o8mKmJ5gFTkXBNc',
  'https://fastly.picsum.photos/id/1050/500/500.jpg?hmac=RTjRfuSRUndu2kdCIsGfJq27Vx6u280W8xaA7R4nFGk',
  'https://fastly.picsum.photos/id/1060/500/500.jpg?hmac=1_Zfj2QnxUoauTpLLb7BO881mQrrsM9pgyEDTuOw-QM',
  'https://fastly.picsum.photos/id/1070/500/500.jpg?hmac=fFiEzBh4MVKg9RRd9A3Rdsbvza9QeuqcnNdsKHJzo-8',
  'https://fastly.picsum.photos/id/1080/500/500.jpg?hmac=yIT2RDfQXaNeihJn27EjmEjuQzADHzr-QtozN0qaz7Y',
];

export const defaultImages = [
  'https://randomuser.me/api/portraits/men/1.jpg',
  'https://randomuser.me/api/portraits/women/2.jpg',
  'https://randomuser.me/api/portraits/men/3.jpg',
  'https://randomuser.me/api/portraits/women/4.jpg',
  'https://randomuser.me/api/portraits/men/5.jpg',
  'https://randomuser.me/api/portraits/women/6.jpg',
  'https://randomuser.me/api/portraits/men/7.jpg',
  'https://randomuser.me/api/portraits/women/8.jpg',
  'https://randomuser.me/api/portraits/men/9.jpg',
  'https://randomuser.me/api/portraits/women/10.jpg',
];
