export const strings = {
  password: 'Password',
  email: 'Email',
  instagram: 'Instagram',
  or: 'OR',
  gender: 'Gender :',
  firstName: 'FirstName',
  lastName: 'LastName',
  phoneNo: 'Phone No.',
  dob: 'Select DOB',
  confirmPassword: 'ConfirmPassword',
  signUp: 'Sign Up',
  haveAccount: 'Have an Account?',
  signHere: 'Sign in here',
  login: 'Sign In',
  DoNotAccount: 'Already have an account? ',
  signUpHere: 'Sign up here.',
  googleSignup: 'Sign Up with Google',
  submit: 'Submit',
  language: 'Select Language',
  primary: 'primary',
};
