export const strings = {
  password: 'Password',
  email: 'Email',
  instagram: 'Instagram',
  or: 'OR',
  gender: 'Gender :',
  firstName: 'FirstName',
  lastName: 'LastName',
  phoneNo: 'Phone No.',
  dob: 'Select DOB',
  confirmPassword: 'ConfirmPassword',
  signUp: 'Sign Up',
  haveAccount: 'Have an Account?',
  signHere: 'Sign in here',
  login: 'Sign In',
  DoNotAccount: 'Already have an account? ',
  signUpHere: 'Sign up here.',
  googleSignup: 'Sign Up with Google',
  submit: 'Submit',
  language: 'Select Language',
  primary: 'primary',
  accept: 'Accept',
  delete: 'Delete',
  loading: 'Loading...',
  noNotification: 'No Notifications',
  suggested_account: 'Suggested Account',
  no_users_found: 'No users found',
  home: 'Home',
  search: 'Search',
  add_post: 'Add Post',
  notification: 'Notification',
  profile: 'Profile',
  logout: 'Logout',
  create_post: 'Create Post',
  comments: 'Comments',
  liked_by: ' Liked by',
  edit_profile: 'Edit Profile',
  following: 'Following',
  followers: 'Followers',
  posts: 'Posts',
  edit: 'Edit Profile',
  noPost: 'No Post',
  no_followers_found: 'No Followers Found',
  no_following_found: 'No Following Found',
};
